name: Build and Push to ECR - Notificaciones

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        run: |
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id=${AWS_ACCESS_KEY_ID}" >> ~/.aws/credentials
          echo "aws_secret_access_key=${AWS_SECRET_ACCESS_KEY}" >> ~/.aws/credentials
          echo "aws_session_token=${AWS_SESSION_TOKEN}" >> ~/.aws/credentials

      - name: Build and push Docker image
        env:
          ECR_URI: ${{ secrets.ECR_URI_NOTIFICACIONES }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SNS_TOPIC_ARN: ${{ secrets.SNS_TOPIC_ARN }}
        run: |
          docker build --build-arg AWS_REGION=$AWS_REGION \
                       --build-arg SNS_TOPIC_ARN=$SNS_TOPIC_ARN \
                       -t notificaciones:latest .
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | \
          docker login --username AWS --password-stdin $ECR_URI
          docker tag notificaciones:latest $ECR_URI:notificaciones
          docker push $ECR_URI:notificaciones